// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using SWD392.Models;

namespace SWD392.Data;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BlogContent> BlogContents { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Child> Children { get; set; }

    public virtual DbSet<ConsultationNote> ConsultationNotes { get; set; }

    public virtual DbSet<DeviationAnalysis> DeviationAnalyses { get; set; }

    public virtual DbSet<Faq> Faqs { get; set; }

    public virtual DbSet<Feedback> Feedbacks { get; set; }

    public virtual DbSet<GrowthIndicator> GrowthIndicators { get; set; }

    public virtual DbSet<MembershipPackage> MembershipPackages { get; set; }

    public virtual DbSet<PaymentTransaction> PaymentTransactions { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<Reply> Replies { get; set; }

    public virtual DbSet<TeethingRecord> TeethingRecords { get; set; }

    public virtual DbSet<Tooth> Teeth { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserMembership> UserMemberships { get; set; }

    public virtual DbSet<VaccinationSchedule> VaccinationSchedules { get; set; }

    public virtual DbSet<Vaccine> Vaccines { get; set; }

    public virtual DbSet<VaccineRecord> VaccineRecords { get; set; }

    public virtual DbSet<WhoGrowthStandard> WhoGrowthStandards { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BlogContent>(entity =>
        {
            entity.HasKey(e => e.BlogContentId).HasName("PK__blog_con__48384C349235FDB1");

            entity.ToTable("blog_contents");

            entity.Property(e => e.BlogContentId).HasColumnName("blog_content_id");
            entity.Property(e => e.AdminId).HasColumnName("admin_id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Likes).HasColumnName("likes");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.ThumbnailUrl)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("thumbnail_url");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("title");
            entity.Property(e => e.Views).HasColumnName("views");

            entity.HasOne(d => d.Admin).WithMany(p => p.BlogContents)
                .HasForeignKey(d => d.AdminId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_blog_contents_admin");

            entity.HasMany(d => d.Categories).WithMany(p => p.BlogContents)
                .UsingEntity<Dictionary<string, object>>(
                    "BlogCategory",
                    r => r.HasOne<Category>().WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_blog_categories_categories"),
                    l => l.HasOne<BlogContent>().WithMany()
                        .HasForeignKey("BlogContentId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_blog_categories_blog_contents"),
                    j =>
                    {
                        j.HasKey("BlogContentId", "CategoryId").HasName("PK__blog_cat__156CA2AFC8068C7F");
                        j.ToTable("blog_categories");
                        j.IndexerProperty<int>("BlogContentId").HasColumnName("blog_content_id");
                        j.IndexerProperty<int>("CategoryId").HasColumnName("category_id");
                    });
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__categori__D54EE9B41867ED4E");

            entity.ToTable("categories");

            entity.Property(e => e.CategoryId).HasColumnName("category_id");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("category_name");
        });

        modelBuilder.Entity<Child>(entity =>
        {
            entity.HasKey(e => e.ChildrenId).HasName("PK__children__1DAECF1881729E05");

            entity.ToTable("children");

            entity.Property(e => e.ChildrenId).HasColumnName("children_id");
            entity.Property(e => e.Allergies)
                .HasMaxLength(255)
                .HasColumnName("allergies");
            entity.Property(e => e.Avatar)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("avatar");
            entity.Property(e => e.BloodType)
                .HasMaxLength(10)
                .HasColumnName("blood_type");
            entity.Property(e => e.ChronicConditions)
                .HasMaxLength(255)
                .HasColumnName("chronic_conditions");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Dob).HasColumnName("dob");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("full_name");
            entity.Property(e => e.Gender)
                .HasMaxLength(50)
                .HasColumnName("gender");
            entity.Property(e => e.MemberId).HasColumnName("member_id");
            entity.Property(e => e.Status)
                .HasDefaultValue(1)
                .HasColumnName("status");

            entity.HasOne(d => d.Member).WithMany(p => p.Children)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_children_users");
        });

        modelBuilder.Entity<ConsultationNote>(entity =>
        {
            entity.HasKey(e => e.ConsultationNoteId).HasName("PK__consulta__C46F4A401CFDC3C5");

            entity.ToTable("consultation_notes");

            entity.Property(e => e.ConsultationNoteId).HasColumnName("consultation_note_id");
            entity.Property(e => e.ChildrenId).HasColumnName("children_id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.DoctorId).HasColumnName("doctor_id");
            entity.Property(e => e.MemberId).HasColumnName("member_id");
            entity.Property(e => e.RecordTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("record_time");

            entity.HasOne(d => d.Children).WithMany(p => p.ConsultationNotes)
                .HasForeignKey(d => d.ChildrenId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_consultation_notes_children");

            entity.HasOne(d => d.Doctor).WithMany(p => p.ConsultationNoteDoctors)
                .HasForeignKey(d => d.DoctorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_consultation_notes_doctor");

            entity.HasOne(d => d.Member).WithMany(p => p.ConsultationNoteMembers)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_consultation_notes_member");
        });

        modelBuilder.Entity<DeviationAnalysis>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Deviatio__3213E83FACDFE037");

            entity.ToTable("Deviation_Analysis");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ComputedValue)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("computed_value");
            entity.Property(e => e.DeviationPercentage)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("deviation_percentage");
            entity.Property(e => e.GrowthRecordId).HasColumnName("growth_record_id");

            entity.HasOne(d => d.GrowthRecord).WithMany(p => p.DeviationAnalyses)
                .HasForeignKey(d => d.GrowthRecordId)
                .HasConstraintName("FK__Deviation__growt__28B808A7");
        });

        modelBuilder.Entity<Faq>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FAQ__3213E83FFE70170F");

            entity.ToTable("FAQ");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Answer)
                .HasMaxLength(255)
                .HasColumnName("answer");
            entity.Property(e => e.Question)
                .HasMaxLength(255)
                .HasColumnName("question");
        });

        modelBuilder.Entity<Feedback>(entity =>
        {
            entity.HasKey(e => e.FeedbackId).HasName("PK__feedback__7A6B2B8C7C5EB085");

            entity.ToTable("feedbacks");

            entity.Property(e => e.FeedbackId).HasColumnName("feedback_id");
            entity.Property(e => e.Content).HasColumnName("content");
            entity.Property(e => e.MemberId).HasColumnName("member_id");
            entity.Property(e => e.Rating).HasColumnName("rating");

            entity.HasOne(d => d.Member).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_feedbacks_users");
        });

        modelBuilder.Entity<GrowthIndicator>(entity =>
        {
            entity.HasKey(e => e.GrowthIndicatorsId).HasName("PK__growth_i__C307B74304FF8E07");

            entity.ToTable("growth_indicators");

            entity.Property(e => e.GrowthIndicatorsId).HasColumnName("growth_indicators_id");
            entity.Property(e => e.Bmi)
                .HasColumnType("decimal(10, 4)")
                .HasColumnName("bmi");
            entity.Property(e => e.ChildrenId).HasColumnName("children_id");
            entity.Property(e => e.Height)
                .HasColumnType("decimal(10, 4)")
                .HasColumnName("height");
            entity.Property(e => e.RecordTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("record_time");
            entity.Property(e => e.Weight)
                .HasColumnType("decimal(10, 4)")
                .HasColumnName("weight");

            entity.HasOne(d => d.Children).WithMany(p => p.GrowthIndicators)
                .HasForeignKey(d => d.ChildrenId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_growth_indicators_children");
        });

        modelBuilder.Entity<MembershipPackage>(entity =>
        {
            entity.HasKey(e => e.MembershipPackageId).HasName("PK__membersh__3BA5AAD990D65CFE");

            entity.ToTable("membership_packages");

            entity.HasIndex(e => e.MembershipPackageName, "UQ__membersh__53772C87AE70D60A").IsUnique();

            entity.Property(e => e.MembershipPackageId).HasColumnName("membership_package_id");
            entity.Property(e => e.AdminId).HasColumnName("admin_id");
            entity.Property(e => e.CreatedTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_time");
            entity.Property(e => e.Image).HasColumnName("image");
            entity.Property(e => e.MembershipPackageName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("membership_package_name");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("price");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.Summary).HasColumnName("summary");
            entity.Property(e => e.ValidityPeriod).HasColumnName("validity_period");
            entity.Property(e => e.YearlyPrice)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("yearly_price");

            entity.HasMany(d => d.Permissions).WithMany(p => p.MembershipPackages)
                .UsingEntity<Dictionary<string, object>>(
                    "PackagePermission",
                    r => r.HasOne<Permission>().WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_package_permissions_permissions"),
                    l => l.HasOne<MembershipPackage>().WithMany()
                        .HasForeignKey("MembershipPackageId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_package_permissions_membership_packages"),
                    j =>
                    {
                        j.HasKey("MembershipPackageId", "PermissionId").HasName("PK__package___85F69B7614F7E11E");
                        j.ToTable("package_permissions");
                        j.IndexerProperty<int>("MembershipPackageId").HasColumnName("membership_package_id");
                        j.IndexerProperty<int>("PermissionId").HasColumnName("permission_id");
                    });
        });

        modelBuilder.Entity<PaymentTransaction>(entity =>
        {
            entity.HasKey(e => e.PaymentTransactionId).HasName("PK__PaymentT__C22AEFE0749B7A1E");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PaymentId).HasMaxLength(100);
            entity.Property(e => e.PreviousMembershipPackageName)
                .HasMaxLength(255)
                .HasColumnName("previous_membership_package_name");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TransactionDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserMembershipId).HasColumnName("user_membership_id");

            entity.HasOne(d => d.MembershipPackage).WithMany(p => p.PaymentTransactions)
                .HasForeignKey(d => d.MembershipPackageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentTransactions_MembershipPackages");

            entity.HasOne(d => d.User).WithMany(p => p.PaymentTransactions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentTransactions_Users");

            entity.HasOne(d => d.UserMembership).WithMany(p => p.PaymentTransactions)
                .HasForeignKey(d => d.UserMembershipId)
                .HasConstraintName("FK_PaymentTransactions_UserMembership");
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasKey(e => e.PermissionId).HasName("PK__permissi__E5331AFAE330F666");

            entity.ToTable("permissions");

            entity.HasIndex(e => e.PermissionName, "UQ__permissi__81C0F5A21BDA3AE4").IsUnique();

            entity.Property(e => e.PermissionId).HasColumnName("permission_id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.PermissionName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("permission_name");
        });

        modelBuilder.Entity<Reply>(entity =>
        {
            entity.HasKey(e => e.ReplyId).HasName("PK__replies__EE405698FAFEA406");

            entity.ToTable("replies");

            entity.Property(e => e.ReplyId).HasColumnName("reply_id");
            entity.Property(e => e.AdminId).HasColumnName("admin_id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.FeedbackId).HasColumnName("feedback_id");

            entity.HasOne(d => d.Admin).WithMany(p => p.Replies)
                .HasForeignKey(d => d.AdminId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_replies_admin");

            entity.HasOne(d => d.Feedback).WithMany(p => p.Replies)
                .HasForeignKey(d => d.FeedbackId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_replies_feedbacks");
        });

        modelBuilder.Entity<TeethingRecord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Teething__3213E83FC9E32CFF");

            entity.ToTable("TeethingRecord");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ChildId).HasColumnName("child_id");
            entity.Property(e => e.EruptionDate)
                .HasColumnType("datetime")
                .HasColumnName("eruption_date");
            entity.Property(e => e.Note)
                .HasMaxLength(255)
                .HasColumnName("note");
            entity.Property(e => e.RecordTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("record_time");
            entity.Property(e => e.ToothId).HasColumnName("tooth_id");

            entity.HasOne(d => d.Child).WithMany(p => p.TeethingRecords)
                .HasForeignKey(d => d.ChildId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TeethingR__child__1B5E0D89");

            entity.HasOne(d => d.Tooth).WithMany(p => p.TeethingRecords)
                .HasForeignKey(d => d.ToothId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TeethingR__tooth__1C5231C2");
        });

        modelBuilder.Entity<Tooth>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Tooth__3213E83F80926536");

            entity.ToTable("Tooth");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.NumberOfTeeth).HasColumnName("number_of_teeth");
            entity.Property(e => e.TeethingPeriod).HasColumnName("teething_period");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__users__B9BE370F263DB4ED");

            entity.ToTable("users");

            entity.HasIndex(e => e.Email, "UQ__users__AB6E61648F5CECDA").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.Address)
                .HasMaxLength(100)
                .HasColumnName("address");
            entity.Property(e => e.Avatar)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("avatar");
            entity.Property(e => e.Country)
                .HasMaxLength(50)
                .HasColumnName("country");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.EmailActivation)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("unactivated")
                .HasColumnName("email_activation");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("full_name");
            entity.Property(e => e.Hospital)
                .HasMaxLength(255)
                .HasColumnName("hospital");
            entity.Property(e => e.LicenseNumber)
                .HasMaxLength(255)
                .HasColumnName("license_number");
            entity.Property(e => e.MembershipPackageId).HasColumnName("membership_package_id");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("password_hash");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("phone_number");
            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("role");
            entity.Property(e => e.Specialization)
                .HasMaxLength(255)
                .HasColumnName("specialization");
            entity.Property(e => e.State)
                .HasMaxLength(50)
                .HasColumnName("state");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.Uid)
                .HasMaxLength(255)
                .HasColumnName("uid");
            entity.Property(e => e.Zipcode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("zipcode");

            entity.HasOne(d => d.MembershipPackage).WithMany(p => p.Users)
                .HasForeignKey(d => d.MembershipPackageId)
                .HasConstraintName("FK_users_membership_packages");
        });

        modelBuilder.Entity<UserMembership>(entity =>
        {
            entity.HasKey(e => e.UserMembershipId).HasName("PK__user_mem__E37A2534766BB024");

            entity.ToTable("user_memberships");

            entity.Property(e => e.UserMembershipId).HasColumnName("user_membership_id");
            entity.Property(e => e.EndDate)
                .HasColumnType("datetime")
                .HasColumnName("end_date");
            entity.Property(e => e.MembershipPackageId).HasColumnName("membership_package_id");
            entity.Property(e => e.StartDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("start_date");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.MembershipPackage).WithMany(p => p.UserMemberships)
                .HasForeignKey(d => d.MembershipPackageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_user_memberships_membership_packages");

            entity.HasOne(d => d.PaymentTransaction).WithMany(p => p.UserMemberships)
                .HasForeignKey(d => d.PaymentTransactionId)
                .HasConstraintName("FK_UserMemberships_PaymentTransactions");

            entity.HasOne(d => d.User).WithMany(p => p.UserMemberships)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_user_memberships_users");
        });

        modelBuilder.Entity<VaccinationSchedule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Vaccinat__3213E83F587A275C");

            entity.ToTable("Vaccination_Schedule");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.RecommendedAgeMonths).HasColumnName("recommended_age_months");
            entity.Property(e => e.VaccineId).HasColumnName("vaccine_id");

            entity.HasOne(d => d.Vaccine).WithMany(p => p.VaccinationSchedules)
                .HasForeignKey(d => d.VaccineId)
                .HasConstraintName("FK__Vaccinati__vacci__25DB9BFC");
        });

        modelBuilder.Entity<Vaccine>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Vaccine__3213E83FA3A6D328");

            entity.ToTable("Vaccine");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.DosesRequired).HasColumnName("doses_required");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<VaccineRecord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__VaccineR__3213E83F34A6CE76");

            entity.ToTable("VaccineRecord");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AdministeredDate)
                .HasColumnType("datetime")
                .HasColumnName("administered_date");
            entity.Property(e => e.ChildId).HasColumnName("child_id");
            entity.Property(e => e.Dose).HasColumnName("dose");
            entity.Property(e => e.NextDoseDate)
                .HasColumnType("datetime")
                .HasColumnName("next_dose_date");
            entity.Property(e => e.VaccineId).HasColumnName("vaccine_id");

            entity.HasOne(d => d.Child).WithMany(p => p.VaccineRecords)
                .HasForeignKey(d => d.ChildId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VaccineRe__child__14B10FFA");

            entity.HasOne(d => d.Vaccine).WithMany(p => p.VaccineRecords)
                .HasForeignKey(d => d.VaccineId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VaccineRecord_Vaccine");
        });

        modelBuilder.Entity<WhoGrowthStandard>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__WHO_Grow__3213E83F75671391");

            entity.ToTable("WHO_Growth_Standards");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AgeMonths).HasColumnName("age_months");
            entity.Property(e => e.BmiAvg)
                .HasColumnType("decimal(10, 4)")
                .HasColumnName("bmi_avg");
            entity.Property(e => e.Gender)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("gender");
            entity.Property(e => e.HeightAvg)
                .HasColumnType("decimal(10, 4)")
                .HasColumnName("height_avg");
            entity.Property(e => e.WeightAvg)
                .HasColumnType("decimal(10, 4)")
                .HasColumnName("weight_avg");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}