// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD392.Models;

public partial class DeviationAnalysis
{
    public int Id { get; set; }

    public int? GrowthRecordId { get; set; }

    public decimal? ComputedValue { get; set; }

    public decimal? DeviationPercentage { get; set; }

    public virtual GrowthIndicator GrowthRecord { get; set; }
}