// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD392.Models;

public partial class Feedback
{
    public int FeedbackId { get; set; }

    public int Rating { get; set; }

    public string Content { get; set; }

    public int MemberId { get; set; }

    public virtual User Member { get; set; }

    public virtual ICollection<Reply> Replies { get; set; } = new List<Reply>();
}