// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD392.Models;

public partial class Paymenttransaction
{
    public int Paymenttransactionid { get; set; }

    public string Paymentid { get; set; }

    public int Userid { get; set; }

    public int Membershippackageid { get; set; }

    public decimal Amount { get; set; }

    public DateTime Transactiondate { get; set; }

    public string Status { get; set; }

    public string PreviousMembershipPackageName { get; set; }

    public int? UserMembershipId { get; set; }

    public virtual MembershipPackage Membershippackage { get; set; }

    public virtual User User { get; set; }

    public virtual UserMembership UserMembership { get; set; }

    public virtual ICollection<UserMembership> UserMemberships { get; set; } = new List<UserMembership>();
}