// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD392.Models;

public partial class PaymentTransaction
{
    public int PaymentTransactionId { get; set; }

    public string PaymentId { get; set; }

    public int UserId { get; set; }

    public int MembershipPackageId { get; set; }

    public decimal Amount { get; set; }

    public DateTime TransactionDate { get; set; }

    public string Status { get; set; }

    public string PreviousMembershipPackageName { get; set; }

    public virtual MembershipPackage MembershipPackage { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<UserMembership> UserMemberships { get; set; } = new List<UserMembership>();
}