// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD392.Models;

public partial class Tooth
{
    public int Id { get; set; }

    public int NumberOfTeeth { get; set; }

    public string TeethingPeriod { get; set; }

    public string Name { get; set; }

    public virtual ICollection<TeethingRecord> TeethingRecords { get; set; } = new List<TeethingRecord>();
}