// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD392.Models;

public partial class UserPermission
{
    public int UserPermissionId { get; set; }

    public int UserMembershipId { get; set; }

    public int PermissionId { get; set; }

    public string PermissionName { get; set; }

    public string PermissionDescription { get; set; }

    public virtual Permission Permission { get; set; }

    public virtual UserMembership UserMembership { get; set; }
}