// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD392.Models;

public partial class WhoGrowthStandard
{
    public int Id { get; set; }

    public int? AgeMonths { get; set; }

    public string Gender { get; set; }

    public decimal HeightAvg { get; set; }

    public decimal WeightAvg { get; set; }

    public decimal BmiAvg { get; set; }
}